### ISSUE TITLE
Does undmg handle symlinks

### ISSUE THREAD

**Issue by bwolf** [matthewbauer/undmg#3]
I tried it with a dmg containing relative symlinks like https://github.com/qutebrowser/qutebrowser/releases/download/v1.6.1/qutebrowser-1.6.1.dmg and all symlinks aren't present. Instead it seems the links are followed and copied, which does not work in the case of directory links. Is this correct and is there a easy way to fix it?

**Comment by matthewbauer** [comment]
Yeah, it doesn't look like that's supported. I think it should be pretty easy to fix. The code that handles this logic is right here:

https://github.com/matthewbauer/undmg/blob/2b62ecf137dfc2faa0798ad4794cbe87ee54d3ff/hfslib.c#L724-L735

I'm not sure what "type" value is coming up here

**Comment by bwolf** [comment]
I'm currently looking at extractAllInFolder (`hfslib.c`), adding debug information. The function `hfs_untar` is unused.

**Comment by lilyball** [comment]
I just ran into this issue. I tried to use this to unpack a `.app` and none of the symlinks were preserved.

**Comment by sikmir** [comment]
@matthewbauer Could you please make a release (1.0.4) to get this fix available in nixpkgs? I ran into this issue with many *.dmg.

**Comment by matthewbauer** [comment]
done in https://github.com/NixOS/nixpkgs/pull/94106
