### ISSUE TITLE
Segfault using shell redirection but not without

### ISSUE THREAD

**Issue by cyounkins** [matthewbauer/undmg#8]
Source: https://sourceforge.net/projects/freepascal/files/Mac%20OS%20X/3.2.0/fpc-3.2.0.intel-macosx.dmg/download

```
craig@mbp > undmg < /nix/store/8chj4dry45cpq77nhb6w6yq0nw787v65-fpc-3.2.0.intel-macosx.dmg
fish: Job 1, 'undmg < /nix/store/8chj4dry45cp…' terminated by signal SIGSEGV (Address boundary error)
craig@mbp > rm *
craig@mbp > undmg /nix/store/8chj4dry45cpq77nhb6w6yq0nw787v65-fpc-3.2.0.intel-macosx.dmg
craig@mbp > ls
'Getting Started (Intel).rtf'   License.txt   ReadMe.txt  "What's New.txt"   fpc-3.2.0-intel-macosx.pkg
```

I see the other segfault issues but they all seem to use the documented usage pattern of shell redirection. In my case no segfault occurred when I had undmg read the file directly.

**Comment by matthewbauer** [comment]
closing with https://github.com/matthewbauer/undmg/commit/97f07e8b1e17b0b7a4eb7bda640d3e7482265e6e

**Comment by cyounkins** [comment]
I see the commit just disables the ability to use stdin. Do you have any idea what would cause this issue? Were you able to reproduce it? Thanks!

**Comment by matthewbauer** [comment]
Yes, I was able to repro. I'm not sure but I suspect it has something to do with fseek not working on stdin.
